### ISSUE TITLE
The daemon stops the moment I pull out the plug.

### ISSUE THREAD

**Issue by Exorust** [AdnanHodzic/auto-cpufreq#16] opened 2020-01-06 11:20 UTC
Everytime I pull out the plug or plug the laptop in, the daemon crashes.
![Screenshot from 2020-01-06 16-49-58](https://user-images.githubusercontent.com/20578676/71815165-97eec980-30a4-11ea-9c1d-7d75ad68343c.png)

**Comment by AdnanHodzic** [comment] 2020-01-07 07:32
As you suggested, I think problem is identical to: https://github.com/AdnanHodzic/auto-cpufreq/issues/21

As I suggested there, I think these problems could be related to using older package version for "psuti"l which were installed from apt repos:

`sudo pip3 show psutil | grep -i version`

Recommended version should be >= 5.5.1

Hence, could you please try upgrading both using pip3 by running:

`sudo pip3 install --upgrade psutil`

And let me know if the problem still persits after this?

**Comment by AdnanHodzic** [comment] 2020-01-07 18:07
Issue is duplicate of: https://github.com/AdnanHodzic/auto-cpufreq/issues/12

**Closed by AdnanHodzic** 2020-01-07 18:07 UTC
