### ISSUE TITLE
[feature request] Make an editable config file

### ISSUE THREAD

**Issue by Exorust** [AdnanHodzic/auto-cpufreq#30] opened 2020-01-10 07:54 UTC
How about making a config file to specify the powersave vs performance and turbo-boost constants, which are currently hardcoded in the set_powersave and mon_powersave and related functions.

This could be a long term goal and would expose tweak-ability in a format similar to tlp.

**Comment by AdnanHodzic** [comment] 2020-01-12 07:16
I like this idea. My idea (which I had in plan for one of the future releases) was to allow users to specify these themselves using CLI. Something like having another "advanced" mode which would allow you to easily/interactively tweak these to your own liking.

**Comment by AdnanHodzic** [comment] 2020-01-12 07:27
Duplicate of #26 let's continue the discussion there.

**Closed by AdnanHodzic** 2020-01-12 07:27 UTC
